crypto:
	gcc -o Executables/crypto.out crypto.c file_if.c user_file_if.c

crypto_attack:
	gcc -o Executables/crypto_attack.out crypto.c file_if.c crypto_attack.c
	
crypto_eff:
	gcc -o Executables/crypto_eff.out crypto.c crypto_eff.c

crypto_test:
	gcc -o Executables/crypto_eff.out crypto.c crypto_test.c

	

