/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class datastore_DatastoreInterface */

#ifndef _Included_datastore_DatastoreInterface
#define _Included_datastore_DatastoreInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     datastore_DatastoreInterface
 * Method:    init_data_store
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_datastore_DatastoreInterface_init_1data_1store
  (JNIEnv *, jclass);

/*
 * Class:     datastore_DatastoreInterface
 * Method:    destroy_data_store
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_datastore_DatastoreInterface_destroy_1data_1store
  (JNIEnv *, jclass);

/*
 * Class:     datastore_DatastoreInterface
 * Method:    write_data
 * Signature: (ILjava/lang/String;CI)I
 */
JNIEXPORT jint JNICALL Java_datastore_DatastoreInterface_write_1data
  (JNIEnv *, jclass, jint, jstring, jchar, jint);

/*
 * Class:     datastore_DatastoreInterface
 * Method:    update_data
 * Signature: (IILjava/lang/String;CI)I
 */
JNIEXPORT jint JNICALL Java_datastore_DatastoreInterface_update_1data
  (JNIEnv *, jclass, jint, jint, jstring, jchar, jint);

/*
 * Class:     datastore_DatastoreInterface
 * Method:    read_data
 * Signature: (ILdatastore/DataTuple;)V
 */
JNIEXPORT void JNICALL Java_datastore_DatastoreInterface_read_1data
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
